#!/bin/bash
#  *
#  *                       EVEREST
#  *    =============================================
#  *     Created: Mar 2023
#  *     Authors: ngl@zurich.ibm.com
#  *
#  *     Description:
#  *       Bash wrapper to offer a CLI for everest-basecamp
#  *
#  *

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# TODO?
# source venv/bin/activate
export PYTHONPATH=$SCRIPT_DIR
python3 ebc/cli.py "$@"
